### ISSUE TITLE
Replaced the data, but still ran the same iterations 

### ISSUE THREAD

**Issue by rdhpn** [jameshskoh/girvan-newman#1]
1 2                                         2 1                                         1 3                                         3 1                                         4 1                                         1 4                                         4 2                                         2 4                                         4 3                                         3 4                                         3 5                                         5 3                                         5 7                                         7 5                                         5 6                                         6 5                                         6 7                                         7 6

**Comment by rdhpn** [comment]
I am the learner that you graded Java Capstone project.  I tried to test the data in question on your program to see if it would receive same results, but it still keeps running numerous iterations even though there are a few nodes of them.

**Comment by jameshskoh** [comment]
I did some simplification and my implementation requires the data set to use consecutive numbers from 0 to n-1, you can simply change label 7 to 0 and my project should run.

The data files should be put at src/main/resource/data
If you want to use the test suite then you should put it at src/test/resource/data

I have tested your dataset myself and get 24.0 myself. It turns out my implementation counted the value twice.

You will need to run the program in debug mode to see all the data.

To help with your debugging, you can get this 24.0 by setting breakpoint at `Solver.killEdges()` method. This method will only run when the program has done calculating all flow and betweenness data.

Once you have reached this breakpoint, you may see that the edgesToKill should contain 1 edge number* (when I run it, it was #7).

You can verify this edge number indeed corresponds to node #3 and #5 by reading s.edgesData > edge number > endpoints.

Finally, using this edge number, you can find its betweenness value at p.betw. The #-th element of the array is the value.

**Comment by jameshskoh** [comment]
My implementation takes a starting point and runs BFS through all nodes connected to it, while "accumulating" "flow" along the way. In order to "recollect" these flow data and calculate betweenness, it has to start from the nodes furthest away from the starting point. This essentially require me to create an inverted list compared to the BFS.

In my implementation, all starting points are iterated in `Solver.calcBetw()`, while each BFS search is implemented in `Solver.incFlowAndBetwViaBFS()`. The BFS list is naturally implemented with a queue, while the inverted list is implemented with a stack.

Good luck.

**Comment by jameshskoh** [comment]
Here's a mathematical validation that indeed edge 3-5 should be 12.0 (or 24.0).

1. A shortest path (set of shortest paths) for a source-dest always adds 1.0 to the edge it passes through
    a. A shortest path through 3-5 adds a weight of 1.0 to it
    b. A set of shortest paths with the same source-dest through 3-5 adds a total weight of 1.0 to it (e.g. for source-dest 2-5: 2135 gives 0.5, 2435 gives 0.5).
2. There are 4 nodes on the left, 3 nodes on the right, and the nodes on one side must pass through 3-5 to reach the nodes on the other side. There can be no other ways.
3. By permutation or combination (排列与组合), you will have 4P3 = 24 permutations (directed) or 4C3 = 12 combinations (undirected) of pairs.
4. Since each pair must correspond to a weight of 1.0 to edge 3-5, the betweenness should be 24.0 (directed, counted twice) or 12.0 (undirected).

**Comment by jameshskoh** [comment]
I copied your message here.

Here are 15 one way answers: 3-5, 3-5-6, 3-5-7, 1-3-5, 1-3-5-6, 1-3-5-7, 4-3-5, 4-3-5-6, 4-3-5-7, 2-1-3-5, 2-1-3-5-6, 2-1-3-5-7, 2-4-3-5, 2-4-3-5-6, 2-4-3-5-7. Perhaps when you talked about 0.5 weight, you meant that I could only count one way, not both directions. That's how I got the answer. But neither way I could get 12 as the total flow number. Perhaps you can clarify me with a manual count

Indeed counting in two directions is not the issue here, if you count a path from two ways, you count all paths from two ways, and their relative ranking would stay the same.

The issue is that for **a particular source-dest combination, all its shortest paths have to share a weight of 1.0**. I believe your 15.0 comes from these paths:
2135 and 2435 for source-dest 2-5
21356 and 24356 for source-dest 2-6
21357 and 24357 for source-dest 2-7

For each source-dest, the total weight it can give is 1.0, and this 1.0 has to be split between 2135 and 2435. Meaning that 21 gets 0.5, 24 gets 0.5, while 35 gets 0.5 **twice**.

If you were to give 2135 and 2435 a weight of 1.0, then 21 gets 1.0, 24 gets 1.0, while 35 gets 1.0 **twice**. And when you get this double counting for the above three, you get 15.0.

Indeed this is what I'm talking about when I say about being "not fair" to others. **Imagine** there are another two nodes 8 and 9 that has 20 equally short paths (slightly exaggerated), and they happens to go through edge 1-2. The network would be heavily skewed towards the shortest paths for 8 to 9, and edge 1-2 will receive an additional 20.0 betweenness **just because of 8 and 9 only**. Thus, splitting the weight of 1.0 across different shortest paths should be a "fairer" option.

**Comment by rdhpn** [comment]
Even if we follow your way of calculations, this edge might have flow of
12.  But for other edges results still don't match with the one as shown in
the video. I didn't test on your program though. I tested on mine and here
is what I found for edge between 1 & 2 with total flow of 4-2/3, not 3.

Shortest path   flow  flow buildup
[1, 2] 1.0 1.0
[3, 1, 2] 0.5 1.5
[5, 3, 1, 2] 0.3333333333333333 1.8333333333333333
[6, 5, 3, 1, 2] 0.25 2.083333333333333
[7, 5, 3, 1, 2] 0.25 2.333333333333333
[2, 1] 1.0 3.333333333333333
[2, 1, 3] 0.5 3.833333333333333
[2, 1, 3, 5] 0.3333333333333333 4.166666666666666
[2, 1, 3, 5, 6] 0.25 4.416666666666666
[2, 1, 3, 5, 7] 0.25 4.666666666666666

Even though it appears to work on edge between 3 & 5 now:
Shortest path   flow  flow buildup
[1, 3, 5] 0.5 0.5
[1, 3, 5, 6] 0.3333333333333333 0.8333333333333333
[1, 3, 5, 7] 0.3333333333333333 1.1666666666666665
[2, 1, 3, 5] 0.3333333333333333 1.4999999999999998
[2, 4, 3, 5] 0.3333333333333333 1.833333333333333
[2, 1, 3, 5, 6] 0.25 2.083333333333333
[2, 4, 3, 5, 6] 0.25 2.333333333333333
[2, 1, 3, 5, 7] 0.25 2.583333333333333 [2, 4, 3, 5, 7] 0.25
2.833333333333333
[3, 5] 1.0 3.833333333333333 [3, 5, 6] 0.5 4.333333333333333
[3, 5, 7] 0.5 4.833333333333333 [4, 3, 5] 0.5 5.333333333333333
[4, 3, 5, 6] 0.3333333333333333 5.666666666666666
[4, 3, 5, 7] 0.3333333333333333 5.999999999999999
[5, 3, 1] 0.5 6.499999999999999 [5, 3, 1, 2] 0.3333333333333333
6.833333333333332 [5, 3, 4, 2] 0.3333333333333333 7.166666666666665
[5, 3] 1.0 8.166666666666664
[5, 3, 4] 0.5 8.666666666666664
[6, 5, 3, 1] 0.3333333333333333 8.999999999999998
[6, 5, 3, 1, 2] 0.25 9.249999999999998
[6, 5, 3, 4, 2] 0.25 9.499999999999998
[6, 5, 3] 0.5 9.999999999999998
[6, 5, 3, 4] 0.3333333333333333 10.333333333333332
[7, 5, 3, 1] 0.3333333333333333 10.666666666666666
[7, 5, 3, 1, 2] 0.25 10.916666666666666
[7, 5, 3, 4, 2] 0.25 11.166666666666666 [7, 5, 3] 0.5 11.666666666666666
[7, 5, 3, 4] 0.3333333333333333 12.0


Others don't match as well.

**Comment by rdhpn** [comment]
I see that you meant differently.  Even just for same source-dest only
gets.  Between 1&2 we would receive 5 instead of 3 because I don't see any
same sourc-dest in here:

Shortest path   flow  flow buildup
[1, 2] 1 1
[3, 1, 2] 1 2
[5, 3, 1, 2] 1 3
[6, 5, 3, 1, 2] 1 4
[7, 5, 3, 1, 2] 1 5

**Comment by rdhpn** [comment]
I see that you meant differently.  Even when same source-dest can only get
1, for edge between 1&2 we would still receive 5 instead of 3 because I
don't see any same source-dest in here:

Shortest path   flow  flow buildup
[1, 2] 1 1
[3, 1, 2] 1 2
[5, 3, 1, 2] 1 3
[6, 5, 3, 1, 2] 1 4
[7, 5, 3, 1, 2] 1 5

**Comment by jameshskoh** [comment]
Judging by your result, I probably can't help much here ...

What I can see is there are fractional values of 1/6 and I think it's odd because there are only two branches right? So even when you have fractions they should be 1/2 at most.

I suggest you try doing this by hand and compare it to your code, it will probably bring you some insight. Also, you can refer to the textbook I suggested previously, they explained the algorithm in full detail.
